### ISSUE TITLE
Rename Images

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-os#33]
Our CrowPi image is not specific to CrowPi.

I would suggest a renaming.

Done 
- [ ] CrowPi-Image -> Pi4jOS
   - [ ] password pi4j
- [ ]  Picade-Image -> PicadeOS
- [ ] (upcoming) GameHatImage -> GameHatOS
- [ ] all READMEs (like template-project, crowpi-tutorial) are updated

**Comment by FDelporte** [comment]
Detail remark about the name... We always use Pi4J with capital J, but that means it would be Pi4JOS pronounced as pi-four-jos. Or should we call it Pi4J-OS?
And PicadeOS is also Pi4J- and Java-specific, so maybe we could end up with this list?
* Pi4J-Basic-OS
* Pi4J-Picade-OS
* Pi4J-GameHat-OS
* ...

**Comment by ppmathis** [comment]
I've just discussed this with @DieterHolz too and the current `crowpi` image flavor does contain some things specific to the CrowPi, e.g. mapping a DHT11 kernel driver on pin 4 within `/boot/config.txt`. From a technical perspective I guess we could:

- Instead of just using the `base` directory in both existing images, actually build `base` as a dedicated image
- Keep the existing `crowpi` and `picade` image flavors, but build them on top of the output of the `base` image
- Add any additional image flavors in the future as needed, e.g. `gamehat`

And then assign whatever fancy marketing names we want to these flavors, e.g. link to the `crowpi` flavor and call it `Pi4J-CrowPi-OS`. So the base image would ship with:

- the launcher scripts (e.g. `java-kiosk`) for easily running applications
- existing example projects for both JavaFX and Pi4J
- default WiFi configuration for easy deployment, even without a screen
- pre-configured goodies like VNC and custom passwords
- dynamic wallpaper script
- a generic `/boot/config.txt` which works for all sorts of hardware (e.g. enable I²C, SPI, VC4 V3D, ...)

And then each specific image can extend that image, e.g. add additional `config.txt` entries, install any DT overlays or whatever. We are already pretty close to that structure, so it should be fairly easy to implement.

**Comment by FDelporte** [comment]
love it!

**Comment by DieterHolz** [comment]
Great!

**Comment by FDelporte** [comment]
Has been implemented by @DieterHolz and is now available in three versions as documented on https://pi4j.com/pi4j-os/
